const h = React.createElement;
return {
  apply(ctx) {
    const slots = ctx.get('slots');
    const timer = ctx.get('timer');
    if (!slots) return;
    const disposeStyles = styles.insert(`.mj-card{border:1px solid var(--border-subtle,#d8dde5);background:var(--surface-raised,#fff);border-radius:8px;padding:14px;max-width:720px;color:var(--text-primary,#17202b);font:13px/1.35 system-ui,sans-serif}.mj-card-head,.mj-card-foot,.mj-score{display:flex;align-items:center;justify-content:space-between;gap:10px}.mj-card-head strong{font-size:15px}.mj-state{color:var(--text-secondary,#667085)}.mj-board{height:150px;margin:12px 0;border-radius:6px;background:#23735d;position:relative;display:grid;place-items:center;color:#e8f5ef;overflow:hidden}.mj-board:before{content:'';position:absolute;inset:22px;border:1px solid rgba(255,255,255,.24);border-radius:4px}.mj-center{position:relative;text-align:center}.mj-seats{position:absolute;inset:8px;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;gap:4px}.mj-seat{font-size:11px;display:flex;flex-direction:column;gap:2px}.mj-seat:nth-child(2),.mj-seat:nth-child(4){text-align:right}.mj-score{font-variant-numeric:tabular-nums;font-size:12px}.mj-event{color:var(--text-secondary,#667085);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mj-actions{display:flex;gap:8px}.mj-button{border:1px solid var(--border-subtle,#cfd5df);background:transparent;border-radius:6px;padding:6px 9px;color:inherit;cursor:pointer}.mj-button.primary{background:#195c4a;color:#fff;border-color:#195c4a}.mj-detail{margin-top:10px;max-height:260px;overflow:auto;border-top:1px solid var(--border-subtle,#d8dde5);padding-top:10px}.mj-detail pre{white-space:pre-wrap;font-size:11px;margin:0}`);
    function parseBlock(block) { if (!block) return {}; if (typeof block.argsRaw === 'string') { try { return JSON.parse(block.argsRaw); } catch (_) {} } const content = Array.isArray(block.content) ? block.content : []; const text = content.filter((item) => item && item.type === 'text').map((item) => item.text).join(''); try { return JSON.parse(text); } catch (_) { return {}; } }
    function derivedSessionId(callId) { return 'mj-' + String(callId || '').replace(/[^a-zA-Z0-9_-]/g, '-'); }
    function eventText(event) { if (!event) return '等待牌局事件'; const labels = { start_game: '牌局开始', start_kyoku: '局开始', tsumo: '摸牌', dahai: '打牌', chi: '吃', pon: '碰', daiminkan: '大明杠', ankan: '暗杠', kakan: '加杠', reach: '立直', hora: '和牌', ryukyoku: '流局', end_game: '牌局结束' }; return (labels[event.type] || event.type || '事件') + (event.pai ? ' · ' + event.pai : ''); }
    function View(props) { const [state, setState] = React.useState(null); const [open, setOpen] = React.useState(false); const [exported, setExported] = React.useState(null); const input = parseBlock(props.block); const sessionId = input.sessionId || derivedSessionId(props.callId); React.useEffect(() => { let alive = true; async function refresh() { try { const next = await host.call('mahjong.status', { sessionId }); if (alive) setState(next); } catch (_) {} } refresh(); if (timer) return timer.interval(refresh, 1200); }, [sessionId]); const data = state || input || {}; const scores = Array.isArray(data.scores) ? data.scores : [25000,25000,25000,25000]; const events = Array.isArray(data.events) ? data.events : []; async function exportLog() { try { setExported(await host.call('mahjong.export', { sessionId })); setOpen(true); } catch (error) { setExported({ error: String(error) }); setOpen(true); } } return h('div', { className: 'mj-card' }, h('div', { className: 'mj-card-head' }, h('strong', null, '日本麻将对局'), h('span', { className: 'mj-state' }, data.status || 'starting')), h('div', { className: 'mj-board' }, h('div', { className: 'mj-seats' }, scores.map((score, i) => h('div', { className: 'mj-seat', key: i }, h('span', null, ['东家','南家','西家','北家'][i]), h('b', null, Number(score).toLocaleString())))), h('div', { className: 'mj-center' }, h('strong', null, data.seed ? 'Seed ' + data.seed : '等待'), h('div', null, '紧凑牌桌预览'))), h('div', { className: 'mj-score' }, h('span', { className: 'mj-event' }, '最近动作：' + eventText(data.lastEvent)), h('span', null, '事件 ' + Number(data.eventCount || events.length || 0))), h('div', { className: 'mj-card-foot' }, h('span', { className: 'mj-event' }, data.error || (data.status === 'ended' ? '对局完成，可查看完整牌谱' : '规则引擎与模型决策进行中')), h('div', { className: 'mj-actions' }, h('button', { className: 'mj-button primary', type: 'button', onClick: () => setOpen(!open) }, open ? '收起牌桌' : '展开牌桌'), data.status === 'ended' ? h('button', { className: 'mj-button', type: 'button', onClick: exportLog }, '导出 MJAI') : null)), open ? h('div', { className: 'mj-detail' }, h('pre', null, JSON.stringify(exported || { sessionId, status: data.status, scores, lastEvent: data.lastEvent, violations: data.violations, fallbacks: data.fallbacks, events: events.slice(-60) }, null, 2))) : null); }
    const inject = slots.inject('tool.call.toolview', () => slots.register({ name: 'tool.call.toolview', key: 'mahjong_start' }, (props) => h(View, props)));
    ctx.effect(() => () => { if (disposeStyles) disposeStyles(); if (inject) inject(); }, 'mahjong-card');
  }
};